Repository open-sauced/guestbook, pull requests merged in 2023-10, with the labels that each got.

#128 Add @Ajiboso-Adeola as a contributor.
  .all-contributorsrc
  README.md
Labels: 💡 feature

#133 feat: add CODEOWNERS file
  .github/CODEOWNERS
Labels: 💡 feature

#116 feat: adding translation rules to README
  README.md
  i18tn-guidelines.md
Labels: 💡 feature

#123 docs: Add "Keeping Branch Up to Date and Resolving Merge Conflicts" section
  README.md
Labels: documentation

#157 fix: translation guide updates
  README.md
  i18n-guidelines.md
Labels: documentation, 🐛 bug

#159 fix: removing the "t" in the first heading
  i18n-guidelines.md
Labels: documentation, 💡 feature

#162 Add solenessa as a contributor
  .all-contributorsrc
  README.md
Labels: 💡 feature
